/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c83bbf93-ad4f-46ab-aadc-f865d6d781ed",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_c9d1tSHII",
    "aws_user_pools_web_client_id": "3lqvlr1mcvv2m7r8vvfccrtgct",
    "oauth": {}
};


export default awsmobile;
